# Generated by Django 2.1.7 on 2019-04-01 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=255)),
                ('unionId', models.CharField(max_length=255)),
                ('nickName', models.CharField(max_length=255)),
                ('gender', models.CharField(default='0', max_length=1)),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('avatarUrl', models.TextField()),
                ('session_key', models.TextField()),
            ],
        ),
    ]
