# Generated by Django 2.1.7 on 2019-04-17 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookshelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webUrl', models.TextField()),
                ('imgUrl', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('sessionId', models.IntegerField()),
                ('writer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('info', models.TextField()),
                ('lastRead', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openId', models.CharField(max_length=255)),
                ('unionId', models.CharField(max_length=255)),
                ('nickName', models.CharField(max_length=255)),
                ('gender', models.CharField(default='0', max_length=1)),
                ('city', models.CharField(max_length=64)),
                ('province', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=32)),
                ('avatarUrl', models.TextField()),
                ('session_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('lifeTime', models.CharField(max_length=64)),
                ('lastModify', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='bookshelf',
            unique_together={('imgUrl', 'sessionId')},
        ),
    ]
