# Generated by Django 2.1.7 on 2019-04-20 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbTables', '0002_readtracker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readtracker',
            name='isSuccess',
            field=models.BooleanField(default=False),
        ),
    ]
